[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "cellpose"
version = "4.1.1"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "scipy",
    "natsort",
    "tifffile",
    "tqdm",
    "torch",
    "torchvision",
    "opencv-python-headless",
    "fastremap",
    "imagecodecs",
    "roifile",
    "fill-voids",
    "segment_anything",
    "pyqtgraph",
    "pyqt6",
    "pyqt6.sip",
    "qtpy",
    "superqt",
    "dask",
    "distributed",
    "dask_image",
    "pyyaml",
    "zarr",
    "dask_jobqueue",
    "bokeh",
    "pyarrow",
    "nd2",
    "pynrrd",
    "bioimageio.core",
]

[project.scripts]
cellpose = "cellpose.__main__:main"
