[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "cellacdc"
version = "1.7.1"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "opencv-python-headless",
    "natsort",
    "h5py",
    "scikit-image",
    "tqdm",
    "scikit-learn",
    "psutil",
    "boto3",
    "requests",
    "setuptools-scm",
    "matplotlib",
    "sympy",
    "imagecodecs",
    "qtpy",
    "pyqt6",
    "torch",
    "torchvision",
    "segment_anything",
    "sam2",
    "sam3",
]

[project.scripts]
cellacdc = "cellacdc.__main__:run"

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch", marker = "sys_platform != 'darwin'" }]
torchvision = [{ index = "pytorch", marker = "sys_platform != 'darwin'" }]